# Generated by Django 3.0 on 2022-11-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='location',
            new_name='location_name',
        ),
    ]
